### ISSUE TITLE
can not zip chinese filename

### ISSUE THREAD

**Issue by chengshwu** [smihica/pyminizip#23]
pyminizip.compress("D:\\py\\测试文件.txt", None, "D:\\py\\test.zip", "password", 5)

it will give the error  :
Exception "unhandled OSError"
error in opening D:\\py\\测试文件.txt for reading

**Comment by veon82** [comment]
I don't think that this is a issue related to the filename encoding but maybe I ignore some encoding problems on Windows.
 
On my Linux machine it works with python2.7:

![image](https://user-images.githubusercontent.com/12305563/40387080-e0e72794-5e0b-11e8-9813-20bb1a153536.png)

Have you tried with other files?

**Comment by chengshwu** [comment]
the environment is windows7 32,python 3.6.4 .if I want use it ,how should I do?

**Comment by zzm88** [comment]
I also have this issue, with python 3.6 and Vscode in windows 10 64 bit.

**Comment by robo3945** [comment]
Also for me the same problem...

**Comment by chris9740** [comment]
Same with me, Ubuntu 18.04, version Python 3.7.5

**Comment by humygithub** [comment]
Same with me， Windows 7 64bit  +  Python 3.65 64bit
filepath=r"三国.txt"  # error in opening 三国.txt for reading
filepath=r"sanguo.txt"
import pyminizip
pyminizip.compress(filepath, None, "r.zip", "123456", 0)

**Comment by humygithub** [comment]
# Windows 7 64bit + Python 3.65 64bit
from pyminizip import compress
compress("a.txt", None, "a.zip", "123456", 0)
compress("甲.txt", None, "jia.zip", "123456", 0)

result:
Traceback (most recent call last):
  File "C:\Users\dyjxx\Desktop\新的文档 1.py", line 4, in <module>
    compress("甲.txt", None, "jia.zip", "123456", 0)
OSError: error in opening 甲.txt for reading

**Comment by humygithub** [comment]
compress_multiple alse has the same question: cannot process filename with Chinese chars

## Windows 7 64bit + Python 3.65 64bit
from pyminizip import compress_multiple
compress_multiple(["a.txt","b.txt"], [], "ab.zip", "123456", 0)
compress_multiple(["甲.txt","乙.txt"], [], "jiayi.zip", "123456", 0)

## 
## result:
## Traceback (most recent call last):
##   File "C:\Users\dyjxx\Desktop\新的文档 1.py", line 17, in <module>
##     compress_multiple(["甲.txt","乙.txt"], [], "jiayi.zip", "123456", 0)
## OSError: error in opening 甲.txt for reading

**Comment by TaZhao** [comment]
same problem on win10 64bit, python 3.7
if chinese in input file name, compress("副本.txt", None, "jia.zip", "123456", 0)
then get error :
OSError: error in opening 副本.txt for reading

**Comment by chajiuqqq** [comment]
It actually has the problem in Windows platform when the src-path or dist-path **contains any Chinese words** . 
- When src-path contains Chinese words, it raises **OSError: error in closing \<dist file\> (-102)**    
- When you solve the previous problem, but dist-path contains Chinese words, you will get **error in opening xxx(file needed zip)**

However ,it works perfect in MacOS or other Linux platform. What a pity!

**Comment by VIZULR** [comment]
Same problem on win10 64bit, python 3.7 but when the path name includes ö or any other extended characters  
OSError: error in closing
